language: erlang
before_install:
        - sudo apt-get install libpam0g-dev libexpat1-dev
        - tools/travis-generate-pass.sh
        - tools/travis-check-tests-branch.sh
install: tools/travis-build.sh
before_script:
        - tools/travis-setup-db.sh
# script: tools/travis-test.sh
script: echo "skip testing temporarily"

after_success:
        - tar cvzf $TARBALL_NAME -C rel/mongooseim/ .
        - curl --ftp-create-dirs -T $TARBALL_NAME -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_SERVER/mongooseim/$TARBALL_NAME

after_script:
        - cat `ls -1 -d -t apps/ejabberd/logs/ct_run* | head -1`/apps.ejabberd.logs/run.*/suite.log
        - tail -100 dev/mongooseim_node1/log/ejabberd.log
        - if [ -s dev/mongooseim_node1/log/crash.log ]; then cat dev/mongooseim_node1/log/crash.log; fi
        - cat `ls -1 -d -t test/ejabberd_tests/ct_report/ct_run.* | head -1`/ejabberd_tests.*/run.*/suite.log
        - cat dev/mongooseim_node1/etc/ejabberd.cfg
services: redis-server
branches:
        only:
                - master
notifications:
        email: lvzecai@gmail.com
otp_release:
        - R15B03
env:
        global:
                - TARBALL_NAME=${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT:0:6}.tar.gz
        matrix:
                - TEST_CONFIG=odbc_redis DB=mysql

